### ISSUE TITLE
Out of range: map bug in LteMacEnb

### ISSUE THREAD

**Issue by MounaKaroui** [brianmc95/OpenCV2X#9]
Hi @brianmc95,

While I am trying to evaluate LTE-V2X mode 3, mode 4 and ITS-G5. I found the run-time error below: 

![image](https://user-images.githubusercontent.com/11929939/75047293-cd217080-54c6-11ea-9977-71f3fc55b213.png)

I used the following scenario: https://github.com/brianmc95/OpenCV2X/blob/master/scenarios/simulte/omnetpp.ini

I  tried another scenario where I changed to typical Mac Type (not realistic) of simulte, and not D2D, but the problem persist. So, the bug is not in related to LTEMacEnbRealisticD2D. I think that the problem is either in LteMacEnb or LteMacBase. 

Could you help me please to resolve this problem? 

Regards,
Mouna

**Comment by MounaKaroui** [comment]
Hi @brianmc95,
The bug is caused by [ ] operator applied to racStatus_ in Ul Enb scheduler. 
I resolved the bug using find() as follow:
https://github.com/MounaKaroui/artery/commit/1a2ed017b66ec0151474231be7777de27793fff9
Regards, 
Mouna

**Comment by MounaKaroui** [comment]
UE nodes in mode 3 didn't receive messages. I tested mode 3 before and it works but with your modifications, UE nodes do not receive message anymore.

**Comment by brianmc95** [comment]
Hi @MounaKaroui,

Sorry for not getting back to you sooner. So First and foremost the implementation does not have a mode 3 version. Mode 4 is the only developed model, any simuLTE based D2D simulations are based on the original D2D definition as of release 12.  Furthermore, it's most likely that during the development of the model for mode 4 that changes have been made to simuLTE that have impacted the previous implementation which is the cause of your issue. This is something I need to return to fix but is not a priority currently. If you wish to run simulations based on the release 12 D2D model then I would checkout the master version of the original simuLTE. https://github.com/inet-framework/simulte 

Otherwise if you want mode 3 based simulations you will have to develop the model based on release 14. Sorry for the inconvenience at the same time and let me know if you have questions.

**Comment by MounaKaroui** [comment]
Thank you for your answer. I am trying to find a solution for fixing that. Because I am currently developing a multi-technology car  model that cover ITS-G5, mode 3 and mode 4. That's why I need all of these technologies implementation
![carModel](https://user-images.githubusercontent.com/11929939/75163100-f3d9e400-571e-11ea-9c4d-68d5c133899d.png)

**Comment by brianmc95** [comment]
I see but mode 3 in that diagram isn't mode 3 it's actually release 12 D2D which isn't the same thing.

At the current moment in time a mode 3 model hasn't been integrated with the model and as such a car with ITS-G5, mode 3 and mode 4 isn't possible to implement.

If you decide to develop the mode 3 model integrating it with the model would be fantastic. But for the moment ensuring that the model works with the old D2D release 12 simuLTE isn't the highest priority as I said previously.

**Comment by MounaKaroui** [comment]
Ok, I see :)
